name: Build and Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # Adjust the Go version as needed

      - name: Build binaries
        run: |
          mkdir -p build
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/${{ matrix.goos }}-${{ matrix.goarch }}/local-turing main.go

      - name: Archive binaries
        run: |
          zip -r build/local-turing-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}.zip build/${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload release assets
        uses: actions/upload-artifact@v3
        with:
          name: local-turing-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/local-turing-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          path: build

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Release notes for ${{ github.ref_name }}
          files: build/*.zip
